### ISSUE TITLE
Disponibilizar no pypi

### ISSUE THREAD

**Issue by aleprovencio** [daneoshiga/django-oscar-pagseguro#1]
Tudo certo @daneoshiga ?
Me parece que já fez praticamente todo o trabalho para a app aparecer no pypi, deve estar faltando algum detalhe!
Apesar de o requirements.txt aceitar endereços github, fica bem melhor assim pois se torna possível gerar requirements através de diffs do 'pip freeze/list'.

Abraço

**Comment by daneoshiga** [comment]
Olá @aleprovencio, pois eh, eu apenas não fiz isso ainda porque nunca fiz, dei uma olhada ontem e realmente é algo simples, assim que possível subo lá, obrigado.

**Comment by daneoshiga** [comment]
https://pypi.python.org/pypi/django-oscar-pagseguro/

Aí está :smile: 

Aparentemente está ok

**Comment by aleprovencio** [comment]
Desculpa a demora, ficou 10!!
Valeu!
