### ISSUE TITLE
Integração Oscar com PagSeguro!!

### ISSUE THREAD

**Issue by rodolfoagomes** [daneoshiga/django-oscar-pagseguro#2]
Olá, recentemente me procuraram para salvar um projeto que estava a pouco de ser lançado e foi abandonado pelo desenvolvedor, a loja é feita em Oscarcommerce, preciso apenas integrar o com pagseguro, vi que possui uma API para isso, poderia me auxiliar em alguns detalhes, não sou muto familiarizado com Python então talvez precise de alguma ajuda incial, apenas dicas mesmo.

Obrigado

**Comment by daneoshiga** [comment]
Olá rodolfo, pode mandar suas dúvidas, posso tentar ajudar, o Readme do projeto tem uma descrição geral de como usar esse código que fiz para realizar a integração, mas qualquer coisa me avise.
